top_srcdir   = /Users/chiragsanghvi/cluster/httpd-2.4.4
top_builddir = /Users/chiragsanghvi/cluster/httpd-2.4.4
srcdir       = /Users/chiragsanghvi/cluster/httpd-2.4.4/modules/metadata
builddir     = /Users/chiragsanghvi/cluster/httpd-2.4.4/modules/metadata
VPATH        = /Users/chiragsanghvi/cluster/httpd-2.4.4/modules/metadata

include $(top_srcdir)/build/special.mk

