top_srcdir   = /Users/chiragsanghvi/cluster/httpd-2.4.4
top_builddir = /Users/chiragsanghvi/cluster/httpd-2.4.4
srcdir       = /Users/chiragsanghvi/cluster/httpd-2.4.4/modules/examples
builddir     = /Users/chiragsanghvi/cluster/httpd-2.4.4/modules/examples
VPATH        = /Users/chiragsanghvi/cluster/httpd-2.4.4/modules/examples
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
