top_srcdir   = /Users/chiragsanghvi/cluster/httpd-2.4.4
top_builddir = /Users/chiragsanghvi/cluster/httpd-2.4.4
srcdir       = /Users/chiragsanghvi/cluster/httpd-2.4.4/modules/core
builddir     = /Users/chiragsanghvi/cluster/httpd-2.4.4/modules/core
VPATH        = /Users/chiragsanghvi/cluster/httpd-2.4.4/modules/core

include $(top_srcdir)/build/special.mk

