top_srcdir   = /Users/chiragsanghvi/cluster/httpd-2.4.4
top_builddir = /Users/chiragsanghvi/cluster/httpd-2.4.4
srcdir       = /Users/chiragsanghvi/cluster/httpd-2.4.4/server/mpm
builddir     = /Users/chiragsanghvi/cluster/httpd-2.4.4/server/mpm
VPATH        = /Users/chiragsanghvi/cluster/httpd-2.4.4/server/mpm

SUBDIRS = $(MPM_SUBDIRS)

include $(top_builddir)/build/rules.mk
