top_srcdir   = /Users/chiragsanghvi/cluster/httpd-2.4.4
top_builddir = /Users/chiragsanghvi/cluster/httpd-2.4.4
srcdir       = /Users/chiragsanghvi/cluster/httpd-2.4.4/modules/http
builddir     = /Users/chiragsanghvi/cluster/httpd-2.4.4/modules/http
VPATH        = /Users/chiragsanghvi/cluster/httpd-2.4.4/modules/http

include $(top_srcdir)/build/special.mk

