top_srcdir   = /Users/chiragsanghvi/cluster/httpd-2.4.4
top_builddir = /Users/chiragsanghvi/cluster/httpd-2.4.4
srcdir       = /Users/chiragsanghvi/cluster/httpd-2.4.4/server/mpm/event
builddir     = /Users/chiragsanghvi/cluster/httpd-2.4.4/server/mpm/event
VPATH        = /Users/chiragsanghvi/cluster/httpd-2.4.4/server/mpm/event
include $(top_srcdir)/build/special.mk
