top_srcdir   = /Users/chiragsanghvi/cluster/httpd-2.4.4
top_builddir = /Users/chiragsanghvi/cluster/httpd-2.4.4
srcdir       = /Users/chiragsanghvi/cluster/httpd-2.4.4/modules/generators
builddir     = /Users/chiragsanghvi/cluster/httpd-2.4.4/modules/generators
VPATH        = /Users/chiragsanghvi/cluster/httpd-2.4.4/modules/generators

include $(top_srcdir)/build/special.mk

