top_srcdir   = /Users/chiragsanghvi/cluster/httpd-2.4.4
top_builddir = /Users/chiragsanghvi/cluster/httpd-2.4.4
srcdir       = /Users/chiragsanghvi/cluster/httpd-2.4.4/os
builddir     = /Users/chiragsanghvi/cluster/httpd-2.4.4/os
VPATH        = /Users/chiragsanghvi/cluster/httpd-2.4.4/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
