top_srcdir   = /Users/chiragsanghvi/cluster/httpd-2.4.4
top_builddir = /Users/chiragsanghvi/cluster/httpd-2.4.4
srcdir       = /Users/chiragsanghvi/cluster/httpd-2.4.4/modules/aaa
builddir     = /Users/chiragsanghvi/cluster/httpd-2.4.4/modules/aaa
VPATH        = /Users/chiragsanghvi/cluster/httpd-2.4.4/modules/aaa

include $(top_srcdir)/build/special.mk

