top_srcdir   = /Users/chiragsanghvi/cluster/httpd-2.4.4
top_builddir = /Users/chiragsanghvi/cluster/httpd-2.4.4
srcdir       = /Users/chiragsanghvi/cluster/httpd-2.4.4/srclib
builddir     = /Users/chiragsanghvi/cluster/httpd-2.4.4/srclib
VPATH        = /Users/chiragsanghvi/cluster/httpd-2.4.4/srclib

BUILD_SUBDIRS = $(AP_BUILD_SRCLIB_DIRS)
CLEAN_SUBDIRS = $(AP_CLEAN_SRCLIB_DIRS)

include $(top_builddir)/build/rules.mk
