top_srcdir   = /Users/chiragsanghvi/cluster/httpd-2.4.4
top_builddir = /Users/chiragsanghvi/cluster/httpd-2.4.4
srcdir       = /Users/chiragsanghvi/cluster/httpd-2.4.4/modules/cache
builddir     = /Users/chiragsanghvi/cluster/httpd-2.4.4/modules/cache
VPATH        = /Users/chiragsanghvi/cluster/httpd-2.4.4/modules/cache

include $(top_srcdir)/build/special.mk

