top_srcdir   = /Users/chiragsanghvi/cluster/httpd-2.4.4
top_builddir = /Users/chiragsanghvi/cluster/httpd-2.4.4
srcdir       = /Users/chiragsanghvi/cluster/httpd-2.4.4/modules/loggers
builddir     = /Users/chiragsanghvi/cluster/httpd-2.4.4/modules/loggers
VPATH        = /Users/chiragsanghvi/cluster/httpd-2.4.4/modules/loggers

include $(top_srcdir)/build/special.mk

