top_srcdir   = /Users/chiragsanghvi/cluster/httpd-2.4.4
top_builddir = /Users/chiragsanghvi/cluster/httpd-2.4.4
srcdir       = /Users/chiragsanghvi/cluster/httpd-2.4.4/modules/echo
builddir     = /Users/chiragsanghvi/cluster/httpd-2.4.4/modules/echo
VPATH        = /Users/chiragsanghvi/cluster/httpd-2.4.4/modules/echo

include $(top_srcdir)/build/special.mk

