top_srcdir   = /Users/chiragsanghvi/cluster/httpd-2.4.4
top_builddir = /Users/chiragsanghvi/cluster/httpd-2.4.4
srcdir       = /Users/chiragsanghvi/cluster/httpd-2.4.4/modules/arch/unix
builddir     = /Users/chiragsanghvi/cluster/httpd-2.4.4/modules/arch/unix
VPATH        = /Users/chiragsanghvi/cluster/httpd-2.4.4/modules/arch/unix

include $(top_srcdir)/build/special.mk

