top_srcdir   = /Users/chiragsanghvi/cluster/httpd-2.4.4
top_builddir = /Users/chiragsanghvi/cluster/httpd-2.4.4
srcdir       = /Users/chiragsanghvi/cluster/httpd-2.4.4/os/unix
builddir     = /Users/chiragsanghvi/cluster/httpd-2.4.4/os/unix
VPATH        = /Users/chiragsanghvi/cluster/httpd-2.4.4/os/unix

LTLIBRARY_NAME    = libos.la
LTLIBRARY_SOURCES = unixd.c

include $(top_srcdir)/build/ltlib.mk
