top_srcdir   = /Users/chiragsanghvi/cluster/httpd-2.4.4
top_builddir = /Users/chiragsanghvi/cluster/httpd-2.4.4
srcdir       = /Users/chiragsanghvi/cluster/httpd-2.4.4/modules/mappers
builddir     = /Users/chiragsanghvi/cluster/httpd-2.4.4/modules/mappers
VPATH        = /Users/chiragsanghvi/cluster/httpd-2.4.4/modules/mappers

include $(top_srcdir)/build/special.mk

