top_srcdir   = /Users/chiragsanghvi/cluster/httpd-2.4.4
top_builddir = /Users/chiragsanghvi/cluster/httpd-2.4.4
srcdir       = /Users/chiragsanghvi/cluster/httpd-2.4.4/modules/filters
builddir     = /Users/chiragsanghvi/cluster/httpd-2.4.4/modules/filters
VPATH        = /Users/chiragsanghvi/cluster/httpd-2.4.4/modules/filters

include $(top_srcdir)/build/special.mk

